In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1 = [4,5,6,7,8,'pawan', 34.56, True]

In [9]:
a1 = np.array(l1)

In [15]:
a1

array(['4', '5', '6', '7', '8', 'pawan', '34.56', 'True'], dtype='<U32')

In [10]:
a2 = np.array([[1,2,3],[4,5,6]])

In [16]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [17]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [12]:
a1.ndim # total number of dimension

1

In [13]:
a2.ndim

2

In [14]:
a3.ndim

3

In [18]:
a1.size #total number of element

8

In [19]:
a2.size

6

In [20]:
a3.size

9

In [21]:
a1.shape #

(8,)

In [22]:
a2.shape      # 2 row 3 columns

(2, 3)

In [23]:
a3.shape     #  1 matrix  in 3X3

(1, 3, 3)

In [29]:
np.random.randint(2,50, (3,4))

array([[47, 24, 42, 30],
       [ 8, 40, 44, 38],
       [14, 15, 15, 35]])

In [30]:
np.random.randint(2,50, (2,3,4))

array([[[43, 16, 11, 42],
        [47,  7,  5, 27],
        [20,  3, 38, 16]],

       [[12, 20, 48, 31],
        [28,  5, 14, 22],
        [ 8, 21,  9,  9]]])

In [31]:
np.random.rand(2,3)

array([[0.02864101, 0.5080113 , 0.89380694],
       [0.54727485, 0.25588292, 0.30424988]])

In [34]:
a4 = np.random.randn(4,4)                          #(mean = 0, standard deviation = 1, Standard normal deviatio

In [35]:
a4

array([[ 0.64008996,  0.07292066,  0.18106546, -0.77633855],
       [-1.48389011, -0.86594636, -0.02185945,  1.04714078],
       [ 0.30906293,  0.06759595,  0.79144178,  0.03563734],
       [-0.03219114,  1.5422064 , -2.6878499 ,  0.85676582]])

In [36]:
a4.reshape(3,4)

ValueError: cannot reshape array of size 16 into shape (3,4)

In [38]:
a4.reshape(8,2)

array([[ 0.64008996,  0.07292066],
       [ 0.18106546, -0.77633855],
       [-1.48389011, -0.86594636],
       [-0.02185945,  1.04714078],
       [ 0.30906293,  0.06759595],
       [ 0.79144178,  0.03563734],
       [-0.03219114,  1.5422064 ],
       [-2.6878499 ,  0.85676582]])

In [40]:
a4.reshape(16,1)

array([[ 0.64008996],
       [ 0.07292066],
       [ 0.18106546],
       [-0.77633855],
       [-1.48389011],
       [-0.86594636],
       [-0.02185945],
       [ 1.04714078],
       [ 0.30906293],
       [ 0.06759595],
       [ 0.79144178],
       [ 0.03563734],
       [-0.03219114],
       [ 1.5422064 ],
       [-2.6878499 ],
       [ 0.85676582]])

In [42]:
a4.reshape(2,-1)

array([[ 0.64008996,  0.07292066,  0.18106546, -0.77633855, -1.48389011,
        -0.86594636, -0.02185945,  1.04714078],
       [ 0.30906293,  0.06759595,  0.79144178,  0.03563734, -0.03219114,
         1.5422064 , -2.6878499 ,  0.85676582]])

In [43]:
a4.reshape(2,2,4)

array([[[ 0.64008996,  0.07292066,  0.18106546, -0.77633855],
        [-1.48389011, -0.86594636, -0.02185945,  1.04714078]],

       [[ 0.30906293,  0.06759595,  0.79144178,  0.03563734],
        [-0.03219114,  1.5422064 , -2.6878499 ,  0.85676582]]])

In [44]:
a4.reshape(1,1,1,1,1,2,2,4)

array([[[[[[[[ 0.64008996,  0.07292066,  0.18106546, -0.77633855],
             [-1.48389011, -0.86594636, -0.02185945,  1.04714078]],

            [[ 0.30906293,  0.06759595,  0.79144178,  0.03563734],
             [-0.03219114,  1.5422064 , -2.6878499 ,  0.85676582]]]]]]]])

In [45]:
a1

array(['4', '5', '6', '7', '8', 'pawan', '34.56', 'True'], dtype='<U32')

In [46]:
a1[0]

'4'

In [47]:
a1[2:6]

array(['6', '7', '8', 'pawan'], dtype='<U32')

In [48]:
a1[2:6:2]

array(['6', '8'], dtype='<U32')

In [49]:
a1[::-1]

array(['True', '34.56', 'pawan', '8', '7', '6', '5', '4'], dtype='<U32')

In [51]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a2[0]

array([1, 2, 3])

In [55]:
a2[0][0:2]

array([1, 2])

In [57]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [58]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [59]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [61]:
a5 = np.random.randint(2,90,(6,5))

In [62]:
a5

array([[ 5, 45, 68, 59, 56],
       [79, 86, 46, 51, 75],
       [32, 38, 17, 72, 82],
       [63, 60,  8, 33, 61],
       [32, 13, 51, 21, 75],
       [70, 47, 78,  9, 21]])

In [63]:
a5[a5>50]

array([68, 59, 56, 79, 86, 51, 75, 72, 82, 63, 60, 61, 51, 75, 70, 78])

In [64]:
a5

array([[ 5, 45, 68, 59, 56],
       [79, 86, 46, 51, 75],
       [32, 38, 17, 72, 82],
       [63, 60,  8, 33, 61],
       [32, 13, 51, 21, 75],
       [70, 47, 78,  9, 21]])

In [66]:
a5[0,1] = 100

In [67]:
a5

array([[  5, 100,  68,  59,  56],
       [ 79,  86,  46,  51,  75],
       [ 32,  38,  17,  72,  82],
       [ 63,  60,   8,  33,  61],
       [ 32,  13,  51,  21,  75],
       [ 70,  47,  78,   9,  21]])

In [72]:
a6 = np.random.randint(0,3, (3,3))

In [73]:
a6

array([[0, 1, 1],
       [2, 1, 2],
       [2, 0, 2]])

In [69]:
a7 = np.random.randint(0,3, (3,3))

In [74]:
a7

array([[1, 1, 2],
       [0, 1, 0],
       [2, 1, 0]])

In [75]:
a6*a7                           # element wise multiplication

array([[0, 1, 2],
       [0, 1, 0],
       [4, 0, 0]])

In [76]:
a6 @ a7                          # matrix multiplication

array([[2, 2, 0],
       [6, 5, 4],
       [6, 4, 4]])

In [78]:
a6 + 100

array([[100, 101, 101],
       [102, 101, 102],
       [102, 100, 102]])

In [79]:
a6 * 2

array([[0, 2, 2],
       [4, 2, 4],
       [4, 0, 4]])

In [80]:
a6 / 0

C:\Users\Pawan\AppData\Local\Temp/ipykernel_2960/2037726597.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6 / 0
C:\Users\Pawan\AppData\Local\Temp/ipykernel_2960/2037726597.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6 / 0


array([[nan, inf, inf],
       [inf, inf, inf],
       [inf, nan, inf]])

In [81]:
a6**3

array([[0, 1, 1],
       [8, 1, 8],
       [8, 0, 8]], dtype=int32)

In [85]:
a8 = np.zeros((4,4))

In [86]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [88]:
a9 = np.ones((4,4))

In [89]:
a9

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [91]:
a9+ 10

array([[11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.]])

In [92]:
a9 + np.array([1,2,3,4])

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [93]:
a9

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [96]:
np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [97]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [98]:
a6

array([[0, 1, 1],
       [2, 1, 2],
       [2, 0, 2]])

In [99]:
a6.T

array([[0, 2, 2],
       [1, 1, 0],
       [1, 2, 2]])

In [100]:
a5

array([[  5, 100,  68,  59,  56],
       [ 79,  86,  46,  51,  75],
       [ 32,  38,  17,  72,  82],
       [ 63,  60,   8,  33,  61],
       [ 32,  13,  51,  21,  75],
       [ 70,  47,  78,   9,  21]])

In [101]:
np.sqrt(a5)

array([[ 2.23606798, 10.        ,  8.24621125,  7.68114575,  7.48331477],
       [ 8.88819442,  9.2736185 ,  6.78232998,  7.14142843,  8.66025404],
       [ 5.65685425,  6.164414  ,  4.12310563,  8.48528137,  9.05538514],
       [ 7.93725393,  7.74596669,  2.82842712,  5.74456265,  7.81024968],
       [ 5.65685425,  3.60555128,  7.14142843,  4.58257569,  8.66025404],
       [ 8.36660027,  6.8556546 ,  8.83176087,  3.        ,  4.58257569]])

In [102]:
np.exp(a5)

array([[1.48413159e+02, 2.68811714e+43, 3.40427605e+29, 4.20121040e+25,
        2.09165950e+24],
       [2.03828107e+34, 2.23524660e+37, 9.49611942e+19, 1.40934908e+22,
        3.73324200e+32],
       [7.89629602e+13, 3.18559318e+16, 2.41549528e+07, 1.85867175e+31,
        4.09399696e+35],
       [2.29378316e+27, 1.14200739e+26, 2.98095799e+03, 2.14643580e+14,
        3.10429794e+26],
       [7.89629602e+13, 4.42413392e+05, 1.40934908e+22, 1.31881573e+09,
        3.73324200e+32],
       [2.51543867e+30, 2.58131289e+20, 7.49841700e+33, 8.10308393e+03,
        1.31881573e+09]])

In [103]:
np.log10(a5)

array([[0.69897   , 2.        , 1.83250891, 1.77085201, 1.74818803],
       [1.89762709, 1.93449845, 1.66275783, 1.70757018, 1.87506126],
       [1.50514998, 1.5797836 , 1.23044892, 1.8573325 , 1.91381385],
       [1.79934055, 1.77815125, 0.90308999, 1.51851394, 1.78532984],
       [1.50514998, 1.11394335, 1.70757018, 1.32221929, 1.87506126],
       [1.84509804, 1.67209786, 1.8920946 , 0.95424251, 1.32221929]])

In [106]:
list(range(0,10, 2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [107]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [114]:
np.linspace(2,3, num = 50,retstep = True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [115]:
np.logspace(2,4, num = 4, base = 10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [116]:
np.eye(5)               # identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [118]:
pip install cufflinks

Note: you may need to restart the kernel to use updated packages.Collecting cufflinks
  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68734 sha256=cb35835bacdf318b7257219f5be97e6dff6841bce582a8026fdfae0773d342ab
  Stored in directory: c:\users\pawan\appdata\local\pip\cache\wheels\29\b4\f8\2fd2206eeeba6ccad8167e4e8894b8c4ec27bf1342037fd136
Successfully built cufflinks



In [4]:
cf.go_offline()

In [13]:
df = pd.DataFrame(np.random.randn(100,3),columns = ['A', 'B', 'C'])

In [14]:
df

A         B         C
0   0.749129 -0.424056 -0.154980
1  -1.107332  0.924964 -0.749995
2   0.401934 -1.156253 -0.342807
3   1.931114  1.495801 -0.050092
4  -0.063762  0.667450 -0.038287
..       ...       ...       ...
95 -0.977887 -0.967449  1.763709
96 -2.288183  0.339653  0.087225
97  1.540529 -0.553704 -0.047205
98 -1.041225 -0.041291  2.332994
99 -1.532190  0.141621 -2.251256

[100 rows x 3 columns]

In [15]:
df.iplot()

In [ ]:
df1 = pd.DataFrame(np.random.randint

In [16]:
df

A         B         C
0   0.749129 -0.424056 -0.154980
1  -1.107332  0.924964 -0.749995
2   0.401934 -1.156253 -0.342807
3   1.931114  1.495801 -0.050092
4  -0.063762  0.667450 -0.038287
..       ...       ...       ...
95 -0.977887 -0.967449  1.763709
96 -2.288183  0.339653  0.087225
97  1.540529 -0.553704 -0.047205
98 -1.041225 -0.041291  2.332994
99 -1.532190  0.141621 -2.251256

[100 rows x 3 columns]

In [17]:
df.iplot(x = 'A', y = 'B', mode = 'markers')

In [18]:
sns.load_dataset('titanic')

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [21]:
df2 = sns.load_dataset('titanic')

In [23]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [24]:
df2.iplot(x = 'age', y = 'fare', mode = 'markers')

In [25]:
df2.iplot(x = 'age', y = 'pclass', mode = 'markers')

In [26]:
df2.iplot(x = 'fare', y = 'pclass', mode = 'markers')

In [27]:
df2.iplot(kind = 'bar', x = 'sex', y = 'survived')