In [2]:
import pandas as pd

In [34]:
data = {'name': ['sudh', 'krish', 'hitesh','telusko'],
        'salary' : [100, 200, 300, 400],
        'mail_id' : ['sudhanshu@ineuron.ai', 'krish@ineuron.ai', 'hitesh@ineuron.ai', 'telusko@ineuron.ai'],
        'addr' : ['blr', 'blr', 'blr', 'mum']
    }

In [36]:
df = pd.DataFrame(data)

In [10]:
data1 = {'name': ['sudh', 'krish', 'hitesh','telusko', 'xyz'],
        'salary' : [100, 200, 300, 400],
        'mail_id' : ['sudhanshu@ineuron.ai', 'krish@ineuron.ai', 'hitesh@ineuron.ai', 'telusko@ineuron.ai'],
        'addr' : ['blr', 'blr', 'blr', 'mum']
    }

In [11]:
pd.DataFrame(data1)

ValueError: All arrays must be of the same length

In [14]:
data = {'name': ['sudh', 'krish', 'hitesh','telusko'],
        'salary' : [100, 200, 300, 400],
        'mail_id' : ['sudhanshu@ineuron.ai', 'krish@ineuron.ai', 'hitesh@ineuron.ai', 'telusko@ineuron.ai'],
        'addr' : ['blr', 'blr', 'blr', 'mum']
    }

In [16]:
df = pd.DataFrame(data, index = [4,5,6,7])

In [17]:
df

name  salary               mail_id addr
4     sudh     100  sudhanshu@ineuron.ai  blr
5    krish     200      krish@ineuron.ai  blr
6   hitesh     300     hitesh@ineuron.ai  blr
7  telusko     400    telusko@ineuron.ai  mum

In [18]:
df.loc[5:6] 

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [25]:
df2 = pd.DataFrame(data, index = ['sudh', 'krish', 'hitesh', 'telusko'])

In [26]:
df2

name  salary               mail_id addr
sudh        sudh     100  sudhanshu@ineuron.ai  blr
krish      krish     200      krish@ineuron.ai  blr
hitesh    hitesh     300     hitesh@ineuron.ai  blr
telusko  telusko     400    telusko@ineuron.ai  mum

In [24]:
df.iloc[1:3] #   '''iloc always takes default index'''#

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [27]:
df

name  salary               mail_id addr
4     sudh     100  sudhanshu@ineuron.ai  blr
5    krish     200      krish@ineuron.ai  blr
6   hitesh     300     hitesh@ineuron.ai  blr
7  telusko     400    telusko@ineuron.ai  mum

In [28]:
data2= {'pf_nu' : [234,45,54465,656],
        'income_tax' : [234,565,767,6778],
        'mobile_no' : [23543,43543,454,5656],
        'courses' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
       }

In [31]:
df2= pd.DataFrame(data2)

In [32]:
df2

pf_nu  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454    web dev 
3    656        6778       5656  blockchian

In [37]:
df

name  salary               mail_id addr
0     sudh     100  sudhanshu@ineuron.ai  blr
1    krish     200      krish@ineuron.ai  blr
2   hitesh     300     hitesh@ineuron.ai  blr
3  telusko     400    telusko@ineuron.ai  mum

In [38]:
pd.concat([df,df2])

name  salary               mail_id addr    pf_nu  income_tax  mobile_no  \
0     sudh   100.0  sudhanshu@ineuron.ai  blr      NaN         NaN        NaN   
1    krish   200.0      krish@ineuron.ai  blr      NaN         NaN        NaN   
2   hitesh   300.0     hitesh@ineuron.ai  blr      NaN         NaN        NaN   
3  telusko   400.0    telusko@ineuron.ai  mum      NaN         NaN        NaN   
0      NaN     NaN                   NaN  NaN    234.0       234.0    23543.0   
1      NaN     NaN                   NaN  NaN     45.0       565.0    43543.0   
2      NaN     NaN                   NaN  NaN  54465.0       767.0      454.0   
3      NaN     NaN                   NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [39]:
pd.concat([df,df2], axis = 1)

name  salary               mail_id addr  pf_nu  income_tax  mobile_no  \
0     sudh     100  sudhanshu@ineuron.ai  blr    234         234      23543   
1    krish     200      krish@ineuron.ai  blr     45         565      43543   
2   hitesh     300     hitesh@ineuron.ai  blr  54465         767        454   
3  telusko     400    telusko@ineuron.ai  mum    656        6778       5656   

      courses  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [40]:
data3 = {'0': ['sudh', 'krish', 'hitesh','telusko'],
        '1' : [100, 200, 300, 400],
        '2' : ['sudhanshu@ineuron.ai', 'krish@ineuron.ai', 'hitesh@ineuron.ai', 'telusko@ineuron.ai'],
        '3' : ['blr', 'blr', 'blr', 'mum']
    }

In [41]:
data4= {'0' : [234,45,54465,656],
        '1' : [234,565,767,6778],
        '2' : [23543,43543,454,5656],
        '3' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
       }

In [42]:
df3 = pd.DataFrame(data3)

In [43]:
df4 = pd.DataFrame(data4)

In [44]:
pd.concat([df3,df4])

0     1                     2           3
0     sudh   100  sudhanshu@ineuron.ai         blr
1    krish   200      krish@ineuron.ai         blr
2   hitesh   300     hitesh@ineuron.ai         blr
3  telusko   400    telusko@ineuron.ai         mum
0      234   234                 23543          ds
1       45   565                 43543     bigdata
2    54465   767                   454    web dev 
3      656  6778                  5656  blockchian

In [45]:
data5 = {
    'emp_id': [101,102,103,104],
    'salary': [234,345,200,400],
    'pf': [23,34,56,78],
}

In [46]:
data6 = {
    'emp_id': [101,102,104,105],
    'mob_no': [3434,345,345,56],
    'house_no': [345,345,345,56]
}

In [48]:
df5 = pd.DataFrame(data5)

In [49]:
df6 = pd.DataFrame(data6)

In [50]:
df5

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [51]:
df6

emp_id  mob_no  house_no
0     101    3434       345
1     102     345       345
2     104     345       345
3     105      56        56

In [52]:
pd.merge(df5,df6) # it perform based on column

emp_id  salary  pf  mob_no  house_no
0     101     234  23    3434       345
1     102     345  34     345       345
2     104     400  78     345       345

In [53]:
pd.merge(df5,df6, how = 'left')

emp_id  salary  pf  mob_no  house_no
0     101     234  23  3434.0     345.0
1     102     345  34   345.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   345.0     345.0

In [54]:
pd.merge(df5,df6, how = 'right')

emp_id  salary    pf  mob_no  house_no
0     101   234.0  23.0    3434       345
1     102   345.0  34.0     345       345
2     104   400.0  78.0     345       345
3     105     NaN   NaN      56        56

In [55]:
pd.merge(df5,df6, how = 'right', on = 'emp_id')

emp_id  salary    pf  mob_no  house_no
0     101   234.0  23.0    3434       345
1     102   345.0  34.0     345       345
2     104   400.0  78.0     345       345
3     105     NaN   NaN      56        56

In [59]:
data7 = {
    'emp_id1': [101,102,103,104],
    'salary': [234,345,200,400],
    'pf': [23,34,56,78],
}

In [61]:
data8 = {
    'emp_id2': [101,102,104,105],
    'mob_no': [3434,345,345,56],
    'house_no': [345,345,345,56]
}

In [60]:
df7 = pd.DataFrame(data7)

In [62]:
df8 = pd.DataFrame(data8)

In [63]:
pd.merge(df7,df8)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [64]:
pd.merge(df7,df8, left_on = 'emp_id1',right_on =  'emp_id2', how = 'inner')

emp_id1  salary  pf  emp_id2  mob_no  house_no
0      101     234  23      101    3434       345
1      102     345  34      102     345       345
2      104     400  78      104     345       345

In [82]:
data9 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data10  = {'emp_id' : [101,102,104,105],
          'salary' : [234, 345,200,400],
          'house_nu' : [345,345,345,56]
         }

In [68]:
df9 = pd.DataFrame(data9)

In [83]:
df10 = pd.DataFrame(data10)

In [79]:
pd.merge(df9,df10, on = ['emp_id', 'salary'])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [92]:
data11 = {'emp_id1' : [101,102,103,104],
         'salary1' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data12 = {'emp_id2' : [101,102,104,105],
          'salary2' : [234, 345,200,878],
          'house_nu' : [345,345,345,56]
    }

In [93]:
df11 = pd.DataFrame(data11,index=['a','b','c','d'])

In [94]:
df12 = pd.DataFrame(data12,index=['a','b','c','d'])

In [95]:
df11

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [96]:
df12

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
c      104      200       345
d      105      878        56

In [98]:
df11.join(df12) #join perform based on index, 

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23      101      234       345
b      102      345  34      102      345       345
c      103      200  56      104      200       345
d      104      400  78      105      878        56

In [104]:
df_sales = pd.read_csv(r'C:\Users\Pawan\Downloads\sales_data_final.csv')

In [105]:
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ...         category sub_category  \
0       Africa  ...  Office Supplies      Storage   
1      Oceania  ...  Office Supplies     Supplies   
2         EMEA  ...  Office Supplies      Storage   
3        North  ...  Office Supplies        Paper   
4      Oceania  ...        Furniture  Furnishings   
...        ...  ...              ...          ...   
51285     West  ...  Office Supplies      Binders   
51286   Africa  ...  Office Supplies      Binders   
51287  Central  ...  Office Supplies       Labels   
51288    North  ...  Office Supplies       Labels   
51289     West  ...  Office Supplies    Fasteners   

                                          product_name sales quantity  \
0                                  Tenex Lockers, Blue   408        2   
1                             Acme Trimmer, High Speed   120        3   
2                              Tenex Box, Single Width    66        4   
3                          Enermax Note Cards, Premium    45        3   
4                           Eldon Light Bulb, Duo Pack   114        5   
...                                                ...   ...      ...   
51285  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14        2   
51286          Wilson Jones Hole Reinforcements, Clear     4        1   
51287           Hon Color Coded Labels, 5000 Label Set    26        3   
51288           Hon Legal Exhibit Labels, Alphabetical     7        1   
51289                              Bagged Rubber Bands     3        3   

       discount    profit  shipping_cost  order_priority  year  
0           0.0  106.1400          35.46          Medium  2011  
1           0.1   36.0360           9.72          Medium  2011  
2           0.0   29.6400           8.17            High  2011  
3           0.5  -26.0550           4.82            High  2011  
4           0.1   37.7700           4.70          Medium  2011  
...         ...       ...            ...             ...   ...  
51285       0.2    4.5188           0.89          Medium  2014  
51286       0.0    0.4200           0.49          Medium  2014  
51287       0.0   12.3600           0.35          Medium  2014  
51288       0.0    0.5600           0.20          Medium  2014  
51289       0.2   -0.6048           0.17   

In [106]:
def profit_flag(a):
    if a> 0:
        return 'positive'
    else:
        return 'negative'

In [108]:
profit_flag(-45)

'negative'

In [109]:
profit_flag(45)

'positive'

In [110]:
df_sales['flag_profit'] = df_sales['profit'].apply(profit_flag)

In [111]:
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ... sub_category  \
0       Africa  ...      Storage   
1      Oceania  ...     Supplies   
2         EMEA  ...      Storage   
3        North  ...        Paper   
4      Oceania  ...  Furnishings   
...        ...  ...          ...   
51285     West  ...      Binders   
51286   Africa  ...      Binders   
51287  Central  ...       Labels   
51288    North  ...       Labels   
51289     West  ...    Fasteners   

                                          product_name sales quantity  \
0                                  Tenex Lockers, Blue   408        2   
1                             Acme Trimmer, High Speed   120        3   
2                              Tenex Box, Single Width    66        4   
3                          Enermax Note Cards, Premium    45        3   
4                           Eldon Light Bulb, Duo Pack   114        5   
...                                                ...   ...      ...   
51285  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14        2   
51286          Wilson Jones Hole Reinforcements, Clear     4        1   
51287           Hon Color Coded Labels, 5000 Label Set    26        3   
51288           Hon Legal Exhibit Labels, Alphabetical     7        1   
51289                              Bagged Rubber Bands     3        3   

      discount    profit  shipping_cost  order_priority  year flag_profit  
0          0.0  106.1400          35.46          Medium  2011    positive  
1          0.1   36.0360           9.72          Medium  2011    positive  
2          0.0   29.6400           8.17            High  2011    positive  
3          0.5  -26.0550           4.82            High  2011    negative  
4          0.1   37.7700           4.70          Medium  2011    positive  
...        ...       ...            ...             ...   ...         ...  
51285      0.2    4.5188           0.89          Medium  2014    positive  
51286      0.0    0.4200           0.49          Medium  2014    positive  
51287      0.0   12.3600           0.35          Medium  2014    positive  
51288      0.0    0.5600           0.20          Medium  2014    positive  
51289      0.2   -0.6048           0.17          Medium  2014    negative  

[51290 rows x 22 columns]

In [112]:
df_sales['len_customer_name'] = df_sales['customer_name'].apply(len)

In [113]:
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ...                                     product_name sales  \
0       Africa  ...                              Tenex Lockers, Blue   408   
1      Oceania  ...                         Acme Trimmer, High Speed   120   
2         EMEA  ...                          Tenex Box, Single Width    66   
3        North  ...                      Enermax Note Cards, Premium    45   
4      Oceania  ...                       Eldon Light Bulb, Duo Pack   114   
...        ...  ...                                              ...   ...   
51285     West  ...  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14   
51286   Africa  ...          Wilson Jones Hole Reinforcements, Clear     4   
51287  Central  ...           Hon Color Coded Labels, 5000 Label Set    26   
51288    North  ...           Hon Legal Exhibit Labels, Alphabetical     7   
51289     West  ...                              Bagged Rubber Bands     3   

      quantity discount    profit  shipping_cost  order_priority  year  \
0            2      0.0  106.1400          35.46          Medium  2011   
1            3      0.1   36.0360           9.72          Medium  2011   
2            4      0.0   29.6400           8.17            High  2011   
3            3      0.5  -26.0550           4.82            High  2011   
4            5      0.1   37.7700           4.70          Medium  2011   
...        ...      ...       ...            ...             ...   ...   
51285        2      0.2    4.5188           0.89          Medium  2014   
51286        1      0.0    0.4200           0.49          Medium  2014   
51287        3      0.0   12.3600           0.35          Medium  2014   
51288        1      0.0    0.5600           0.20          Medium  2014   
51289        3      0.2   -0.6048           0.17          Medium  2014   

       flag_profit len_customer_name  
0         positive                15  
1         positive                11  
2         positive                13  
3         negative                12  
4         positive                11  
...            ...               ...  
51285     positive                10  
51286     positive                 9  
51287     positive                16  
51288     positive                13  
51289     negativ

In [114]:
def quantity_flag(a):
    if a < 10:
        return 'low'
    elif a > 10 and a < 20:
        return 'medium'
    else:
        return 'high'

In [115]:
df_sales['flag_quantity'] = df_sales['quantity'].apply(quantity_flag)

In [117]:
df_sales.head(20)

order_id order_date ship_date       ship_mode      customer_name  \
0      AG-2011-2040   1/1/2011  1/6/2011  Standard Class    Toby Braunhardt   
1     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
2      HU-2011-1220   1/1/2011  1/5/2011    Second Class      Annie Thurman   
3   IT-2011-3647632   1/1/2011  1/5/2011    Second Class       Eugene Moren   
4     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
5     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
6      CA-2011-1510   1/2/2011  1/6/2011  Standard Class    Magdelene Morse   
7     IN-2011-79397   1/3/2011  1/3/2011        Same Day        Kean Nguyen   
8     ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
9      IZ-2011-4680   1/3/2011  1/7/2011  Standard Class   Lindsay Williams   
10    IN-2011-65159   1/3/2011  1/7/2011    Second Class       Larry Blacks   
11    IN-2011-65159   1/3/2011  1/7/2011    Second Class       Larry Blacks   
12  ES-2011-4869686   1/3/2011  1/7/2011  Standard Class  Dorothy Dickinson   
13    IN-2011-33652   1/3/2011  1/9/2011  Standard Class      Dennis Pardue   
14    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
15   MX-2011-160234   1/3/2011  1/7/2011  Standard Class   Stewart Visinsky   
16      IR-2011-770   1/3/2011  1/7/2011  Standard Class      Jas O'Carroll   
17    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
18    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
19    ID-2011-12596   1/3/2011  1/8/2011  Standard Class       Chris McAfee   

        segment              state         country  market          region  \
0      Consumer        Constantine         Algeria  Africa          Africa   
1      Consumer    New South Wales       Australia    APAC         Oceania   
2      Consumer           Budapest         Hungary    EMEA            EMEA   
3   Home Office          Stockholm          Sweden      EU           North   
4      Consumer    New South Wales       Australia    APAC         Oceania   
5      Consumer    New South Wales       Australia    APAC         Oceania   
6      Consumer            Ontario          Canada  Canada          Canada   
7     Corporate    New South Wales       Australia    APAC         Oceania   
8      Consumer           Auckland     New Zealand    APAC         Oceania   
9     Corporate             Ninawa            Iraq    EMEA            EMEA   
10     Consumer   National Capital     Philippines    APAC  Southeast Asia   
11     Consumer   National Capital     Philippines    APAC  Southeast Asia   
12     Consumer            England  United Kingdom      EU           North   
13  Home Office            Sarawak        Malaysia    APAC  Southeast Asia   
14     Consumer           Auckland     New Zealand    APAC         Oceania   
15     Consumer          Guatemala       Guatemala   LATAM         Central   
16     Consumer               Yazd            Iran    EMEA            EMEA   
17     Consumer           Auckland     New Zealand    APAC         Oceania   
18     Consumer           Auckland     New Zealand    APAC         Oceania   
19     Consumer  Nakhon Ratchasima        Thailand    APAC  Southeast Asia   

    ... sales quantity discount    profit shipping_cost  order_priority  year  \
0   ...   408        2     0.00  106.1400         35.46          Medium  2011   
1   ...   120        3     0.10   36.0360          9.72          Medium  2011   
2   ...    66        4     0.00   29.6400          8.17            High  2011   
3   ...    45        3     0.50  -26.0550          4.82            High  2011   
4   ...   114        5     0.10   37.7700          4.70          Medium  2011   
5   ...    55        2     0.10   15.3420          1.80          Medium  2011   
6   ...   314        1     0.00    3.1200         24.10          Medium  2011   
7   ...   276        1     0.10  110.4120        125.32        C

In [118]:
df_sales['square_quantity'] = df_sales['quantity'].apply(lambda a : a**2)

In [119]:
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ... quantity discount    profit shipping_cost order_priority  \
0       Africa  ...        2      0.0  106.1400         35.46         Medium   
1      Oceania  ...        3      0.1   36.0360          9.72         Medium   
2         EMEA  ...        4      0.0   29.6400          8.17           High   
3        North  ...        3      0.5  -26.0550          4.82           High   
4      Oceania  ...        5      0.1   37.7700          4.70         Medium   
...        ...  ...      ...      ...       ...           ...            ...   
51285     West  ...        2      0.2    4.5188          0.89         Medium   
51286   Africa  ...        1      0.0    0.4200          0.49         Medium   
51287  Central  ...        3      0.0   12.3600          0.35         Medium   
51288    North  ...        1      0.0    0.5600          0.20         Medium   
51289     West  ...        3      0.2   -0.6048          0.17         Medium   

       year  flag_profit  len_customer_name  flag_quantity square_quantity  
0      2011     positive                 15            low               4  
1      2011     positive                 11            low               9  
2      2011     positive                 13            low              16  
3      2011     negative                 12            low               9  
4      2011     positive                 11            low              25  
...     ...          ...                ...            ...             ...  
51285  2014     positive                 10            low               4  
51286  2014     positive                  9            low               1  
51287  2014     positive                 16            low               9  
51288  2014     positive                 13            low               1  
51289  2014     negative                 13            low               9  

[51290 rows x 25 columns]

In [120]:
import numpy as np

In [121]:
np.array([2,3,4,5])

array([2, 3, 4, 5])

In [122]:
type(np.array([2,3,4,5]))

numpy.ndarray

In [124]:
np.array([[2,3,4],[4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [125]:
type(np.array([[2,3,4],[4,5,6]]))

numpy.ndarray

In [126]:
np.array([[1,2,3,4],[2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [127]:
l = [[1,2,3,4],[2,3,4,5]]

In [128]:
l[0]

[1, 2, 3, 4]

In [129]:
l[0][0]

1

In [137]:
a = np.array([3,4,5,6], ndmin = 5)

In [138]:
a

array([[[[[3, 4, 5, 6]]]]])

In [135]:
a1 = np.array([3,4,5,6], ndmin = 3)

In [136]:
a1

array([[[3, 4, 5, 6]]])

In [139]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [140]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [141]:
arr.ndim

2

In [148]:
np.random.randint(1,10,(4,4))

array([[2, 7, 8, 3],
       [8, 7, 6, 9],
       [4, 2, 5, 5],
       [7, 7, 3, 2]])

In [149]:
np.random.randint(1,10,(4,4,2))

array([[[6, 7],
        [6, 8],
        [7, 1],
        [5, 4]],

       [[8, 4],
        [1, 5],
        [6, 6],
        [7, 7]],

       [[6, 1],
        [5, 6],
        [4, 2],
        [6, 6]],

       [[1, 6],
        [5, 8],
        [3, 4],
        [4, 5]]])

In [152]:
# Task : 1) about Fitbit Band

# Question:1 read this dataset in pandas, mysql, and MongoDB
#2) while creating a table in mysql dont use manual approach to create it, always use a automation 
     ##hint: use csvkit library to automate thus task and to load a data in bulk in your mysql

#3) convert all the datas available in dataset to timestamp format in pandas and in MySql you to convert 
#4) find out in the dataset that how many unique ids we have
#5) which id is one of the active id that you have in whole dataset
#6) how many of them have not logged there activity find out in terms of Ids
#7) find out who is the laziest person ids that we have in dataset
#8) explore over an internet that how much calories burn is required for healthy person and find 
#9) how many person are not a regular person with respect to activity try to find out
#10) 
#
#
#
#
#
#